### ISSUE TITLE
dante editor

### ISSUE THREAD

**Issue by zhuraavl** [piratebroadcast/backpacker#1]
Hi! You editor worked?
I try to make it work, copy your code, but nothing happens.

**Comment by jessewaites** [comment]
USe the original, Ill delete my fork of it.

https://github.com/michelson/Dante

You gotta require underscorejs to get it to work, thats how I got it to
work.

On Mon, Dec 7, 2015 at 10:32 PM, Andrey notifications@github.com wrote:

> Hi! You editor worked?
> I try to make it work, copy your code, but nothing happens.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/piratebroadcast/backpacker/issues/1.

## 

Jesse Waites
JesseWaites.com

**Comment by zhuraavl** [comment]
That is, it is not enough to connect? We need something else to do?

If you have the opportunity, please tell me. I'm very novice. I got to make it work, but it keeps the positions from the second time and destroying the application if you try to edit an entry with a picture

**Comment by jessewaites** [comment]
Oh I never got it to work all the way, I moved on to something else. I
would try tailing the rails development log and watching what happens or
posting to StackOverflow about it. IF you do post and get a good answer,
please sent it to me as I would like to know.

On Mon, Dec 7, 2015 at 10:53 PM, Andrey notifications@github.com wrote:

> That is, it is not enough to connect? We need something else to do?
> 
> If you have the opportunity, please tell me. I'm very novice. I got to
> make it work, but it keeps the positions from the second time and
> destroying the application if you try to edit an entry with a picture
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/piratebroadcast/backpacker/issues/1#issuecomment-162751408
> .

## 

Jesse Waites
JesseWaites.com

**Comment by zhuraavl** [comment]
Okey, thank
